# Generated by Django 4.1.6 on 2023-04-18 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Chapter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("number", models.IntegerField()),
                ("views", models.IntegerField()),
                ("content", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("userid", models.BigIntegerField(default=0)),
                ("name", models.CharField(max_length=255)),
                ("description", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Subcription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.IntegerField()),
                ("months", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Title",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("userid", models.BigIntegerField(default=0)),
                ("name", models.CharField(max_length=255)),
                ("author", models.CharField(max_length=255)),
                ("description", models.CharField(max_length=255)),
                ("fee", models.BooleanField()),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
                ("totalViews", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=255)),
                ("password", models.CharField(max_length=255)),
                ("email", models.CharField(max_length=255)),
                ("isAdmin", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="Viewed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("userid", models.BigIntegerField(default=0)),
                ("view_at", models.DateTimeField()),
                (
                    "chapterId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="content_model.chapter",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PaidSubcription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("userid", models.BigIntegerField(default=0)),
                ("start_at", models.DateTimeField()),
                (
                    "subcriptionId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="content_model.subcription",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Liked",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("userid", models.BigIntegerField(default=0)),
                (
                    "titleId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="content_model.title",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GenreList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "genreId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="content_model.genre",
                    ),
                ),
                (
                    "titleId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="content_model.title",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="chapter",
            name="titleId",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="content_model.title"
            ),
        ),
    ]
