# Generated by Django 4.1.6 on 2023-04-18 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "content_model",
            "0002_rename_isadmin_user_admin_user_token_alter_user_id_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="viewed", name="views", field=models.IntegerField(default=0),
        ),
    ]
