# Generated by Django 4.2 on 2023-04-25 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_model', '0006_alter_title_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='content',
            field=models.TextField(),
        ),
    ]
