# Generated by Django 4.2 on 2023-04-15 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=255)),
                ('admin', models.BooleanField()),
                ('email', models.CharField(max_length=255)),
            ],
        ),
    ]
