# Generated by Django 4.2 on 2023-04-21 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_accountid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.IntegerField(default=100000)),
                ('months', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='PaidSubscription',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField()),
                ('paid', models.BooleanField()),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.subscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
